targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
          schema: todo_f|lib/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: todo_f|lib/graphql/schema.graphql
